/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  labs: [
    {
      type: `category`,
      label: `Labs`,
      collapsed: false,
      link: {
        type: `doc`,
        id: `labs/index`
      },
      items:[
        "labs/hello-world/index",
      ]
    }
  ],
  syllabus: [
    {
      type: `category`,
      label: `Syllabus`,
      link: {
        type: `doc`,
        id: `syllabus/info`
      },
      items: [
        {
          type: "autogenerated",
          dirName: "syllabus",
        },
      ],
    },
  ],
  notes: [
    "course-notes/index",
    "course-notes/git/index",
    "course-notes/python"
  ]
};

module.exports = sidebars;
