/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  labs: [
    "labs/intro",
    {
      type: "category",
      label: "Labs",
      items: [
        "labs/hello-world/index",
        "labs/data-analytics-ideas/index",
      ],
    },
  ],
  syllabus: [
    {
      type: `category`,
      label: `Syllabus`,
      items: [
        {
          type: "autogenerated",
          dirName: "syllabus",
        },
      ],
    },
  ],
  notes: [
    {
      type: `category`,
      label: `Notes`,
      link: {type: `doc`, id: "course-notes/index"},
      collapsed: false,
      items: [
        "course-notes/git/index",
        "course-notes/python"
      ],
    }
  ]
};

module.exports = sidebars;
