/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coursework: [
    {
      type: `autogenerated`,
      dirName: `.`,
    }
    // "index",
    // {
    //   type: `category`,
    //   label: `Git - Hello World`,
    //   link: {
    //     type: `doc`,
    //     id: `hello-world/index`,
    //   },
    //   items: [
    //     {
    //       type: `autogenerated`,
    //       dirName: `1.hello-world`,
    //     },
    //   ],
    // },
    // `my-story/index`,
    // {
    //   type: `category`,
    //   label: `Python Exercises`,
    //   link: {
    //     type: `doc`,
    //     id: `python-exercises/index`,
    //   },
    //   items: [
    //     {
    //       type: `autogenerated`,
    //       dirName: `3.python-exercises`,
    //     },
    //   ],
    // },
  ],
};

module.exports = sidebars;
