/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  env: [
    {
      type: `category`,
      label: `Environment Setup`,
      collapsed: false,
      link: {
        type: `doc`,
        id: `env-setup/index`
      },
      items:[
        {
          type: "autogenerated",
          dirName: "env-setup",
        },
      ]
    },
  ],
  code: [
    'code-style',
  ]
};

module.exports = sidebars;
